#!/usr/bin/env sh

module_name=$1

mkdir $module_name || { echo "Could not create $module_name."; exit 1; }

cd $module_name

cat <<-EOF > $module_name.tla
---- MODULE $module_name ----
EXTENDS Integers, Sequences, TLC
CONSTANTS MaxQueueSize

(*--algorithm message_queue
variables cheese = MaxQueueSize;
begin
end algorithm; *)

====
EOF

cat <<-EOF > model1.cfg
SPECIFICATION
    Spec
CONSTANT
    MaxQueueSize <- ConstMaxQueueSize
\* INVARIANT
\*     BoundedQueue
\* PROPERTY
\*     Termination
EOF

cat <<-EOF > model1.tla
---- MODULE model1 ----
EXTENDS $module_name, TLC

ConstMaxQueueSize == 2

====
EOF

cat <<-EOF > .gitignore
states
EOF

echo "Created module $module_name"
